version: '3.7'

services:
  web:
    build: 
        context: ./QuickChat
        dockerfile: Dockerfile.prod
    image: furkanax/quickchat
    command: gunicorn QuickChat.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    image: furkanax/nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
